package com.generativimt12.myring;
import android.Manifest; import android.app.Activity; import android.content.*; import android.content.pm.PackageManager; import android.database.Cursor; import android.media.RingtoneManager; import android.net.Uri; import android.os.Bundle; import android.provider.ContactsContract; import android.provider.Settings; import android.view.Gravity; import android.widget.*; import java.io.*;

public class MainActivity extends Activity {
 private static final int PICK_AUDIO=42, REQ_STORAGE=43, REQ_PHONE=44, PICK_CONTACT=45, PICK_PERSONAL_AUDIO=46, REQ_CONTACTS=47;
 private SharedPreferences prefs; private TextView status; private Button testButton; private boolean testPlaying=false; private String pendingContactKey;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("myring",MODE_PRIVATE);if(android.os.Build.VERSION.SDK_INT>=23){if(checkSelfPermission(Manifest.permission.READ_PHONE_STATE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_PHONE_STATE},REQ_PHONE);else if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},REQ_CONTACTS);}buildUi();if(prefs.getBoolean("armed",false))RingService.ensurePersistent(this);}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,40,32,32);root.setGravity(Gravity.CENTER_HORIZONTAL);
 TextView t=new TextView(this);t.setText("Myring");t.setTextSize(30);t.setGravity(Gravity.CENTER);root.addView(t);
 TextView d=new TextView(this);d.setText("צלצול שיחה נכנסת בלבד\nללא חייגן וללא Accessibility");d.setTextSize(18);d.setGravity(Gravity.CENTER);root.addView(d);
 status=new TextView(this);status.setPadding(0,30,0,20);root.addView(status);
 Button c=new Button(this);c.setText("בחר צלצול ברירת מחדל");c.setOnClickListener(v->pickAudio(PICK_AUDIO));root.addView(c);
 Button pc=new Button(this);pc.setText("הוסף צלצול לאיש קשר");pc.setOnClickListener(v->pickContact());root.addView(pc);
 Button list=new Button(this);list.setText("נהל צלצולים לאנשי קשר");list.setOnClickListener(v->showContactRingtones());root.addView(list);
 Button a=new Button(this);a.setText("הפעל תיקון צלצול");a.setOnClickListener(v->armFix());root.addView(a);
 Button r=new Button(this);r.setText("שחזר את הצלצול המקורי");r.setOnClickListener(v->restoreOriginal());root.addView(r);
 testButton=new Button(this);testButton.setText("בדיקת הצלצול שנבחר");testButton.setOnClickListener(v->toggleTest());root.addView(testButton);
 setContentView(root);refreshStatus();}
 private void toggleTest(){if(testPlaying){RingService.stopTest(this);testPlaying=false;testButton.setText("בדיקת הצלצול שנבחר");}else{RingService.startTest(this);testPlaying=true;testButton.setText("עצור את בדיקת הצלצול");}}
 private void pickAudio(int request){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,request);}
 private void pickContact(){startActivityForResult(new Intent(Intent.ACTION_PICK,ContactsContract.Contacts.CONTENT_URI),PICK_CONTACT);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;
  if(r==PICK_AUDIO||r==PICK_PERSONAL_AUDIO){Uri u=d.getData();if(r==PICK_AUDIO)saveAudio(u,false,null);else saveAudio(u,true,pendingContactKey);}
  else if(r==PICK_CONTACT){Cursor x=null;try{x=getContentResolver().query(d.getData(),new String[]{ContactsContract.Contacts._ID,ContactsContract.Contacts.DISPLAY_NAME},null,null,null);if(x!=null&&x.moveToFirst()){pendingContactKey=x.getString(0);String name=x.getString(1);prefs.edit().putString("pending_name",name).apply();pickAudio(PICK_PERSONAL_AUDIO);}}finally{if(x!=null)x.close();}}
 }
 private void saveAudio(Uri u,boolean personal,String key){try{String ext=".audio";String mime=getContentResolver().getType(u);if(mime!=null){if(mime.contains("mpeg"))ext=".mp3";else if(mime.contains("wav"))ext=".wav";else if(mime.contains("ogg"))ext=".ogg";else if(mime.contains("aac"))ext=".aac";}String fileName=personal?"contact_ringtone_"+key+ext:"selected_ringtone"+ext;File f=new File(getFilesDir(),fileName);InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new IOException("cannot read");OutputStream out=new FileOutputStream(f);byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();out.close();
  if(personal){String name=prefs.getString("pending_name","איש קשר");prefs.edit().putString("contact_"+key+"_file",f.getAbsolutePath()).putString("contact_"+key+"_name",name).remove("pending_name").apply();Toast.makeText(this,"הצלצול נשמר עבור "+name,Toast.LENGTH_SHORT).show();}else{prefs.edit().putString("ring_file",f.getAbsolutePath()).putString("ring_uri",u.toString()).apply();Toast.makeText(this,"צלצול ברירת המחדל נשמר",Toast.LENGTH_SHORT).show();}refreshStatus();
 }catch(Exception e){Toast.makeText(this,"לא הצלחתי לקרוא את הצלצול: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void showContactRingtones(){StringBuilder s=new StringBuilder();String[] all=prefs.getAll().keySet().toArray(new String[0]);for(String k:all)if(k.startsWith("contact_")&&k.endsWith("_name")){String key=k.substring(8,k.length()-5);s.append("• ").append(prefs.getString(k,"איש קשר")).append("\n");}
  if(s.length()==0){Toast.makeText(this,"עדיין לא הוגדרו צלצולים לאנשי קשר",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("צלצולים לאנשי קשר").setMessage(s.toString()).setPositiveButton("סגור",null).show();}
 private void armFix(){if(android.os.Build.VERSION.SDK_INT>=23&&!Settings.System.canWrite(this)){try{startActivity(new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}Toast.makeText(this,"אשר לאפליקציה שינוי הגדרות מערכת, ואז לחץ שוב",Toast.LENGTH_LONG).show();return;}if(android.os.Build.VERSION.SDK_INT<=28&&checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},REQ_STORAGE);return;}try{Uri silent=SilentRingtone.ensure(this);Uri old=RingtoneManager.getActualDefaultRingtoneUri(this,RingtoneManager.TYPE_RINGTONE);if(old!=null&&!silent.equals(old)&&!prefs.contains("original_uri"))prefs.edit().putString("original_uri",old.toString()).apply();RingtoneManager.setActualDefaultRingtoneUri(this,RingtoneManager.TYPE_RINGTONE,silent);prefs.edit().putBoolean("armed",true).apply();RingService.ensurePersistent(this);refreshStatus();Toast.makeText(this,"התיקון הופעל",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"הפעלת התיקון נכשלה: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void restoreOriginal(){String s=prefs.getString("original_uri",null);if(s==null){Toast.makeText(this,"לא נשמר צלצול מקורי",Toast.LENGTH_SHORT).show();return;}try{RingtoneManager.setActualDefaultRingtoneUri(this,RingtoneManager.TYPE_RINGTONE,Uri.parse(s));prefs.edit().putBoolean("armed",false).apply();RingService.stopPersistent(this);refreshStatus();Toast.makeText(this,"הצלצול המקורי שוחזר",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"שחזור נכשל: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void refreshStatus(){status.setText((prefs.getBoolean("armed",false)?"✓ תיקון פעיל":"○ התיקון אינו פעיל")+"\n"+(prefs.getString("ring_file",null)==null?"לא נבחר צלצול ברירת מחדל":"צלצול ברירת מחדל נבחר"));}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_STORAGE&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)armFix();if(r==REQ_PHONE&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},REQ_CONTACTS);}
}