package com.generativimt12.myring;
import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import android.os.*;import java.io.File;
public class RingService extends Service {
 public static final String START="START",STOP="STOP",TEST="TEST",TEST_STOP="TEST_STOP";
 private static Ringtone directRingtone; private Ringtone ringtone;
 public static void playIncomingDirect(Context c){playIncomingDirect(c,null);} public static void playIncomingDirect(Context c,String preferredPath){stopIncomingDirect();try{String p=preferredPath!=null?preferredPath:c.getSharedPreferences("myring",MODE_PRIVATE).getString("ring_file",null);if(p==null)return;File f=new File(p);if(!f.isFile()||f.length()==0)return;Ringtone r=RingtoneManager.getRingtone(c.getApplicationContext(),Uri.fromFile(f));if(r==null)return;if(Build.VERSION.SDK_INT>=21){r.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());try{r.setLooping(true);}catch(Exception ignored){}}else{try{r.setStreamType(AudioManager.STREAM_RING);}catch(Exception ignored){}}directRingtone=r;r.play();}catch(Exception ignored){directRingtone=null;}}
 public static void stopIncomingDirect(){if(directRingtone!=null){try{directRingtone.stop();}catch(Exception ignored){}directRingtone=null;}}
 public static void startRinging(Context c){start(c,START);}public static void stopRinging(Context c){start(c,STOP);}public static void startTest(Context c){start(c,TEST);}public static void stopTest(Context c){start(c,TEST_STOP);}public static void ensurePersistent(Context c){start(c,null);}public static void stopPersistent(Context c){try{c.stopService(new Intent(c,RingService.class));}catch(Exception ignored){}}
 private static void start(Context c,String action){Intent i=new Intent(c,RingService.class);i.setAction(action);try{if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}catch(Exception ignored){}}
 @Override public void onCreate(){super.onCreate();createChannel();try{startForeground(7,notification());}catch(Exception ignored){}}
 @Override public int onStartCommand(Intent i,int f,int id){String a=i==null?null:i.getAction();if(START.equals(a)||TEST.equals(a))playRingtone();else if(STOP.equals(a)||TEST_STOP.equals(a)){stopRingtone();}return START_STICKY;}
 private void playRingtone(){stopRingtone();String p=getSharedPreferences("myring",MODE_PRIVATE).getString("ring_file",null);if(p==null)return;File f=new File(p);if(!f.isFile()||f.length()==0)return;try{ringtone=RingtoneManager.getRingtone(this,Uri.fromFile(f));if(ringtone==null)return;if(Build.VERSION.SDK_INT>=21)ringtone.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());if(Build.VERSION.SDK_INT>=21){try{ringtone.setLooping(true);}catch(Exception ignored){}}else{try{ringtone.setStreamType(AudioManager.STREAM_RING);}catch(Exception ignored){}}ringtone.play();}catch(Exception e){stopRingtone();}}
 private void stopRingtone(){if(ringtone!=null){try{ringtone.stop();}catch(Exception ignored){}ringtone=null;}}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel("ring","Myring",NotificationManager.IMPORTANCE_LOW);ch.setSound(null,null);NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(n!=null)n.createNotificationChannel(ch);}}
 private Notification notification(){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"ring"):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_lock_silent_mode_off).setContentTitle("Myring").setContentText("מטפל בצלצול השיחה הנכנסת").setOngoing(true).build();}
 @Override public void onDestroy(){stopRingtone();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}